### ISSUE TITLE
Thanks for sharing

### ISSUE THREAD

**Issue by lemmingDev** [derole1/JVSLib#1]
This code is great

Thanks so much for sharing

I was able to use the JVSLib plus examples to convert a standard JVS card into 2 virtual xbox 360 controllers, plus implement button combos to actuate keyboard keys

Basically the same functionality as https://github.com/derole1/JVS2PC but in C# and uses ViGem

I would like to do the same with FASTIO, but there don't seem to be any C# examples of how to interact with iDmacDrv32.dll.
I might try to fumble my way through the C++ code at https://github.com/fatal-bundy/FastIO2KB and see how I go

**Comment by derole1** [comment]
Hi there,

Thank you for the kind words, and glad to hear the library has helped you in your own project :D

I have not dealt with Fast I/O much at all really, so my knowledge is limited.
FastIO2KB seems like a good start. Its reliant on the ttx idmac drivers, which shy of writing your own device driver I dont see a way around.

Wish you luck on the Fast I/O end, wish I could be more helpful, it looks pretty simple providing you dont mind using idmacdrv.
